### ISSUE TITLE
Receiving S3 access denied when running CloudFormation template

### ISSUE THREAD

**Issue by anthony-sarkis-pwc** [aws-solutions-library-samples/guidance-for-meter-data-analytics-on-aws#64]
Receiving S3 access denied when running CloudFormation template here:

https://github.com/aws-solutions-library-samples/guidance-for-meter-data-analytics-on-aws/blob/main/templates/work-load.template.yaml

This includes making your own S3 bucket or leaving the bucket name the default like the instructions state is recommended. This has been verified from multiple accounts and even AWS Support. 

I worked with Mrudhula Balasubramanyan<mrudhula@amazon.com> who verified this is an issue.

Screenshot won't attach, receiving error but here is a copy paste

2023-08-30 16:40:21 UTC-0400 | IntegrationStack | CREATE_FAILED | S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

2023-08-30 16:40:21 UTC-0400 | DataStorageStack | CREATE_FAILED | S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

2023-08-30 16:40:21 UTC-0400 | MeterDataGeneratorStack | CREATE_FAILED | S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

2023-08-30 16:40:20 UTC-0400 | CopyGlueScriptsStack | CREATE_FAILED | S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

Thank you for your help and time

**Comment by SaschaJanssen** [comment]
Please follow the steps in the README of the repo, you need to copy all resources to your S3 bucket.
https://github.com/aws-solutions-library-samples/guidance-for-meter-data-analytics-on-aws/blob/main/README.md If you experience any issues with that please let me know.

**Comment by Destelle22** [comment]
can we download the zip file, unzip it and simply load the whole folder into an s3? Or do we have to run it thru the command line?

**Comment by SaschaJanssen** [comment]
Unfortunately not. As the deployment process includes packaging the lambda source code. This has to be done first, before copying everything to S3.

**Comment by Destelle22** [comment]
So it has to be done via command line and docker?

**Comment by SaschaJanssen** [comment]
Yes. But you can setup a [Cloud9](https://aws.amazon.com/cloud9/) environment, which has all tools preinstalled and you just clone the repo and execute the scripts.

**Comment by Destelle22** [comment]
Ok, Thanks for the clarification and tips!

**Comment by Destelle22** [comment]
One last follow up. For the second part, the create configuration. It says
to adjust the template and store it besides the apply-stack.sh . As I am
working within the Cloud9 environment I can see the folder for the scripts.
Does this mean to store this json file in this folder?

**Comment by Destelle22** [comment]
I work at Subeca under Patrick and Anne. I mentioned that you had pointed me in the correct direction to set this up and they mentioned they knew you. If you have time this week I would love to ask you some questions on this product !

**Comment by SaschaJanssen** [comment]
Sure just drop me an email (or find me on [LinkedIn](https://www.linkedin.com/in/sascha-j/)) and we can agree on a slot to dive deeper.
